name: "🌏 Environment"
description: "Development environment settings"
labels: "🌏 Environment"
body:
  - type: textarea
    attributes:
      label: 🌏 Describe
      description: 현재 상황
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ Tasks
      description: 업무 세분화
    validations:
      required: true
  - type: textarea
    attributes:
      label: 💬 Additional contex
      description: 추가 내용
