name: "\U0001F30F Environment"
description: "Development environment settings"
labels: "\U0001F30F Environment"
body:
  - type: textarea
    attributes:
      label: \U0001F30F Describe
      description: 현재 상황
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ Tasks
      description: 업무 세분화
    validations:
      required: true
  - type: textarea
    attributes:
      label: 💬 Additional contex
      description: 추가 내용
