name: "💡 Feature"
description: "feature request"
labels: "💡 Feature"
body:
  - type: textarea
    attributes:
      label: 💡 Describe
      description: 기능 설명
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ Tasks
      description: 업무 세분화
    validations:
      required: true
  - type: textarea
    attributes:
      label: 💬 Additional contex
      description: 추가 내용
