name: "🔨 Refactor"
description: "Improve the internal structure"
labels: "🔨 Refactor"
body:
  - type: textarea
    attributes:
      label: 🔨 Describe
      description: 리팩터링의 원인 설명
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ Tasks
      description: 업무 세분화
    validations:
      required: true
  - type: textarea
    attributes:
      label: 💬 Additional context
      description: 추가 내용
